# Generated by Django 3.2 on 2023-05-31 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230531_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_born',
            field=models.DateField(default=datetime.datetime(2023, 5, 31, 9, 30, 44, 429249, tzinfo=utc)),
        ),
    ]
