# Generated by Django 3.2 on 2023-06-01 04:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230601_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_born',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 4, 48, 59, 63292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
