# Generated by Django 3.2 on 2023-06-02 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20230601_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_born',
            field=models.DateField(default=datetime.datetime(2023, 6, 2, 6, 33, 25, 595815, tzinfo=utc)),
        ),
    ]
