# Generated by Django 3.2 on 2023-06-07 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20230607_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_born',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 16, 4, 16, 963868, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='+996000000000', max_length=255, null=True),
        ),
    ]
